import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { OrderDetailsProvider } from '@/contexts/OrderDetails';

import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Candle Shop',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="cupcake" lang="en">
      <body className={inter.className}>
        <OrderDetailsProvider>
          <Navbar />
          <main className="content-container">{children}</main>
          <Footer />
        </OrderDetailsProvider>
      </body>
    </html>
  );
}
